trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'My Openshift'
    version: '3.11.0'
- script: |
    oc project testlu
    where oc
    dir ../..
