trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  persistCredentials: true
- task: oc-setup@2
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'My Openshift'
    version: '3.11.0'
- script: |
    oc project testlu
    where oc
    cd ..
    dir
    cd ..
    dir
    cd ..
    dir
    echo %AGENT_TOOLSDIRECTORY%
    C:
    cd C:\hostedtoolcache\windows
    dir
    cd oc
    dir
    cd 3.11.0\x64\
    dir
